services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: vamo-api
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/vamo
      NODE_ENV: production
    ports:
      - "3000:3000"

  mongodb:
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    container_name: vamo-mongodb
    environment:
      MONGO_INITDB_DATABASE: vamo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
